### ISSUE TITLE
Create Supported Exchanges Component

### ISSUE THREAD

**Issue by lucaswalter** [DataDogsMST/web-app#2]
Just merged in the code scaffolds the database and exposes a new endpoint to retrieve them. I think the next step should be making a simple component to retrieve and display the supported exchanges. The api explorer link below lets you view the structure of the response and test it is working.

API Explorer: http://localhost:8080/api/index.html
New Endpoint: http://localhost:8080/api/exchanges (GET)

**Comment by dnhess** [comment]
This is related to branch [wa-2](https://github.com/DataDogsMST/web-app/tree/wa-2) (Still in progress). I made a change to the startup.cs so that it will allow any origin to access the api calls. This may need to be changed in the future to block certain api calls.

**Comment by dnhess** [comment]
Branched merged. Issue closed
