### ISSUE TITLE
Decide Who Will Be Working On Each Module For Scrum Iteration #1

### ISSUE THREAD

**Issue by lucaswalter** [DataDogsMST/web-app#8]
I think we will be most productive for this first iteration if we split the work for each module during this first scrum iteration (from now until the first presentation). Leave a comment here for which module you would like to start on.

**Frontend**
- @dnhess 
- @npv93 

**Backend**
- @lucaswalter
- @jacob-harrison 

**Data Retrieval**
- @Bryan-A-Asher 
- @ColeMallery

**Comment by jacob-harrison** [comment]
I'll take frontend

**Comment by npv93** [comment]
I think I'd be most useful on the frontend

**Comment by npv93** [comment]
It looks like there's room for a few people per job

**Comment by jacob-harrison** [comment]
Dillon, Lucas, and Ash are group leads I think @npv93

**Comment by ColeMallery** [comment]
I'm fine with working on data retrieval

**Comment by npv93** [comment]
Oh i just assumed you were the one already on the list @jacob-harrison . My bad

**Comment by jacob-harrison** [comment]
Haha np
