### ISSUE TITLE
Create PriceAtTimestamp API Endpoint

### ISSUE THREAD

**Issue by lucaswalter** [DataDogsMST/web-app#9]
Creating a PriceAtTimeStamp endpoint will be a great intro into building APIs and will give you a taste of being able to write queries using LINQ. The purpose of this endpoint is to retrieve the closing price of a cryptocurrency trading product given an exchange, trading product, and timestamp.

Here is how I would like to structure the resource for this endpoint:
api/exchange/{exchangeId}/product/{product}/history/{symbol}?at{timestamp}

The values inside the braces correspond the parameters a consumer will provide to us. Here is an example call would look like:

api/exchange/8/product/BTC-USD/history/BTC?at1536252625

This is actually using a combination of two different parameter types. [Path & Query Parameters](https://medium.com/@fullsour/when-should-you-use-path-variable-and-query-parameter-a346790e8a6d)

I know this is a lot to take in so let me know if you have any questions @jacob-harrison 

Here is a basic workflow of the steps that need to be done to add this in:

- [x] Create a new API Controller named HistoricalController (Look how ExchangesController currently works)
- [x] Create a new method that returns an IActionResult called PriceAtTimestamp
- [x] Add a [route attribute](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.1#attribute-routing-with-httpverb-attributes) that matches the resource path from the example I gave
- [ ] Read in in verify that the provided parameters provider are valid
- [x] Write a LINQ query to query, filter, and return the desired candlestick row (I'll help a lot with this)
- [x] Translate the retrieved candlestick into a DTO (Data Transfer Object) to be returned to the consumer

**Comment by lucaswalter** [comment]
@jacob-harrison The code you added looks good,I think the final step for this issue is just building the DTO and returning it to the consumer. At the moment, it is just returning the entity as a json object which has extra data we don't need to be sending back. Look at the example I have in there for users on how to build the DTO and map it to an entity.

**Comment by jacob-harrison** [comment]
@lucaswalter I created the CandlestickDTO and the mapping profile for it. I changed Historical Controller so that the DTO is returned to user.
